import { db } from "@/lib/db";
import React from "react";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@repo/ui/table";
import Link from "next/link";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";

async function getPayouts(username: string) {
  return await db.payout.findMany({
    where: {
      generatedTo: username,
    },
    orderBy: {
      createdAt: "desc",
    },
  });
}
export default async function page() {
  const session = await auth();
  if (!session) {
    redirect("/login");
  }
  const payouts = await getPayouts(session.user.username);
  return (
    <div className="container md:mt-12 mt-6">
      <h1 className="text-lg font-bold md:text-2xl">Your Payouts</h1>
      <p className="text-sm text-muted-foreground">List of recent of payouts</p>

      <div className="mt-6">
        <Table>
          <TableCaption>A list of recently opened bounties.</TableCaption>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[100px]">S.no</TableHead>
              <TableHead>Link</TableHead>
              <TableHead className="text-right">Generated By</TableHead>
              <TableHead className="text-right">Created At</TableHead>
              <TableHead className="text-right">Amount</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {payouts.map((payout, index) => (
              <TableRow key={index}>
                <TableCell className="font-medium">{++index}</TableCell>
                <TableCell>
                  <Link
                    href={payout.link}
                    target="__blank"
                    className="underline hover:text-foreground text-muted-foreground duration-300"
                  >
                    {payout.link}
                  </Link>
                </TableCell>
                <TableCell className="text-right">
                  <Link
                    href={`https://github.com/${payout.generatedBy}`}
                    target="__blank"
                    className="underline hover:text-foreground text-muted-foreground duration-300"
                  >
                    {payout.generatedBy}
                  </Link>
                </TableCell>
                <TableCell className="text-right">
                  {" "}
                  <div className="font-medium">
                    {payout.createdAt.toLocaleDateString()}
                  </div>
                  <div className="hidden text-sm text-muted-foreground md:inline">
                    {payout.createdAt.toLocaleTimeString()}
                  </div>
                </TableCell>
                <TableCell className="text-right">${payout.amount}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
