"use client";
import { Payout } from "@repo/db";
import React from "react";
import { Badge } from "@repo/ui/badge";
import { MoreHorizontal } from "lucide-react";
import { Button } from "@repo/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@repo/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@repo/ui/dropdown";

const PayoutsTable = ({ payouts }: { payouts: Payout[] }) => {
  return (
    <div className="mt-6">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Winner</TableHead>
            <TableHead className="hidden sm:table-cell">Generated By</TableHead>
            <TableHead className="hidden sm:table-cell">Status</TableHead>
            <TableHead className="hidden md:table-cell">Date</TableHead>
            <TableHead className="text-left">Amount</TableHead>
            <TableHead className="text-right">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {payouts.map((payout) => (
            <TableRow key={payout.id}>
              <TableCell>
                <div className="font-medium">{payout.generatedTo}</div>
                <div className="hidden text-sm text-muted-foreground md:inline"></div>
              </TableCell>
              <TableCell className="hidden sm:table-cell">
                {payout.generatedBy}
              </TableCell>
              <TableCell className="hidden sm:table-cell">
                <Badge className="text-xs capitalize" variant="secondary">
                  {payout.status.toLocaleLowerCase().split("_").join(" ")}
                </Badge>
              </TableCell>
              <TableCell className="hidden md:table-cell">
                {payout.createdAt.toLocaleDateString()}
              </TableCell>
              <TableCell className="text-left">${payout.amount}</TableCell>
              <TableCell className="text-right">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button aria-haspopup="true" size="icon" variant="ghost">
                      <MoreHorizontal className="h-4 w-4" />
                      <span className="sr-only">Toggle menu</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuLabel>Coming soon</DropdownMenuLabel>
                    <DropdownMenuItem>-</DropdownMenuItem>
                    <DropdownMenuItem>-</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
      TODO: Button to only serve few on the records at a time
    </div>
  );
};

export default PayoutsTable;
