import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import WalletProviderComponent from "./providers/walletProvider";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WalletProviderComponent>
        <SessionProvider>
          <Toaster />
          <body className={inter.className}>{children}</body>
        </SessionProvider>
      </WalletProviderComponent>
    </html>
  );
}
