import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import WalletProviderComponent from "./providers/walletProvider";
import { Toaster } from "sonner";
import { WalletContextProvider } from "@/providers/walletContextProvider";
import { ThemeProvider } from "@/providers/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <WalletProviderComponent>
            <SessionProvider>
              <Toaster />
              <WalletContextProvider>{children}</WalletContextProvider>
            </SessionProvider>
          </WalletProviderComponent>
        </ThemeProvider>
      </body>
    </html>
  );
}
