import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import WalletProviderWrapper from "@/providers/wallet-proivder";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";

// const inter = Inter({ subsets: ["latin"] });
const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Include all weights
  subsets: ["latin", "latin-ext", "vietnamese"], // Include all available subsets
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={kanit.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <WalletProviderWrapper>
            <SessionProvider>{children}</SessionProvider>
            <Toaster richColors />
          </WalletProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
